/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInTesterRouteImport } from './routes/sign-in-tester'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutDashboardRouteImport } from './routes/_app-layout/dashboard'
import { Route as AppLayoutDashboardClassesRouteImport } from './routes/_app-layout/dashboard/classes'

const SignInTesterRoute = SignInTesterRouteImport.update({
  id: '/sign-in-tester',
  path: '/sign-in-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutDashboardRoute = AppLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutDashboardClassesRoute =
  AppLayoutDashboardClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AppLayoutDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/dashboard': typeof AppLayoutDashboardRouteWithChildren
  '/dashboard/classes': typeof AppLayoutDashboardClassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/dashboard': typeof AppLayoutDashboardRouteWithChildren
  '/dashboard/classes': typeof AppLayoutDashboardClassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/_app-layout/dashboard': typeof AppLayoutDashboardRouteWithChildren
  '/_app-layout/dashboard/classes': typeof AppLayoutDashboardClassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/sign-in-tester'
    | '/dashboard'
    | '/dashboard/classes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/sign-in-tester' | '/dashboard' | '/dashboard/classes'
  id:
    | '__root__'
    | '/'
    | '/_app-layout'
    | '/health'
    | '/sign-in-tester'
    | '/_app-layout/dashboard'
    | '/_app-layout/dashboard/classes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  HealthRoute: typeof HealthRoute
  SignInTesterRoute: typeof SignInTesterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in-tester': {
      id: '/sign-in-tester'
      path: '/sign-in-tester'
      fullPath: '/sign-in-tester'
      preLoaderRoute: typeof SignInTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/dashboard': {
      id: '/_app-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppLayoutDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/dashboard/classes': {
      id: '/_app-layout/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof AppLayoutDashboardClassesRouteImport
      parentRoute: typeof AppLayoutDashboardRoute
    }
  }
}

interface AppLayoutDashboardRouteChildren {
  AppLayoutDashboardClassesRoute: typeof AppLayoutDashboardClassesRoute
}

const AppLayoutDashboardRouteChildren: AppLayoutDashboardRouteChildren = {
  AppLayoutDashboardClassesRoute: AppLayoutDashboardClassesRoute,
}

const AppLayoutDashboardRouteWithChildren =
  AppLayoutDashboardRoute._addFileChildren(AppLayoutDashboardRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutDashboardRoute: typeof AppLayoutDashboardRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutDashboardRoute: AppLayoutDashboardRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  HealthRoute: HealthRoute,
  SignInTesterRoute: SignInTesterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
