/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInTesterRouteImport } from './routes/sign-in-tester'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutDashboardRouteImport } from './routes/_app-layout/dashboard'
import { Route as AppLayoutClassesRouteImport } from './routes/_app-layout/classes'
import { Route as AppLayoutBookingsRouteImport } from './routes/_app-layout/bookings'
import { Route as AppLayoutConsumersUserIdRouteImport } from './routes/_app-layout/consumers.$userId'
import { Route as AppLayoutBusinessesBusinessIdRouteImport } from './routes/_app-layout/businesses.$businessId'

const SignInTesterRoute = SignInTesterRouteImport.update({
  id: '/sign-in-tester',
  path: '/sign-in-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutDashboardRoute = AppLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutClassesRoute = AppLayoutClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutBookingsRoute = AppLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutConsumersUserIdRoute =
  AppLayoutConsumersUserIdRouteImport.update({
    id: '/consumers/$userId',
    path: '/consumers/$userId',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessesBusinessIdRoute =
  AppLayoutBusinessesBusinessIdRouteImport.update({
    id: '/businesses/$businessId',
    path: '/businesses/$businessId',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/bookings': typeof AppLayoutBookingsRoute
  '/classes': typeof AppLayoutClassesRoute
  '/dashboard': typeof AppLayoutDashboardRoute
  '/businesses/$businessId': typeof AppLayoutBusinessesBusinessIdRoute
  '/consumers/$userId': typeof AppLayoutConsumersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/bookings': typeof AppLayoutBookingsRoute
  '/classes': typeof AppLayoutClassesRoute
  '/dashboard': typeof AppLayoutDashboardRoute
  '/businesses/$businessId': typeof AppLayoutBusinessesBusinessIdRoute
  '/consumers/$userId': typeof AppLayoutConsumersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/health': typeof HealthRoute
  '/sign-in-tester': typeof SignInTesterRoute
  '/_app-layout/bookings': typeof AppLayoutBookingsRoute
  '/_app-layout/classes': typeof AppLayoutClassesRoute
  '/_app-layout/dashboard': typeof AppLayoutDashboardRoute
  '/_app-layout/businesses/$businessId': typeof AppLayoutBusinessesBusinessIdRoute
  '/_app-layout/consumers/$userId': typeof AppLayoutConsumersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/sign-in-tester'
    | '/bookings'
    | '/classes'
    | '/dashboard'
    | '/businesses/$businessId'
    | '/consumers/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/sign-in-tester'
    | '/bookings'
    | '/classes'
    | '/dashboard'
    | '/businesses/$businessId'
    | '/consumers/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app-layout'
    | '/health'
    | '/sign-in-tester'
    | '/_app-layout/bookings'
    | '/_app-layout/classes'
    | '/_app-layout/dashboard'
    | '/_app-layout/businesses/$businessId'
    | '/_app-layout/consumers/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  HealthRoute: typeof HealthRoute
  SignInTesterRoute: typeof SignInTesterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in-tester': {
      id: '/sign-in-tester'
      path: '/sign-in-tester'
      fullPath: '/sign-in-tester'
      preLoaderRoute: typeof SignInTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/dashboard': {
      id: '/_app-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppLayoutDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/classes': {
      id: '/_app-layout/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppLayoutClassesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/bookings': {
      id: '/_app-layout/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppLayoutBookingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/consumers/$userId': {
      id: '/_app-layout/consumers/$userId'
      path: '/consumers/$userId'
      fullPath: '/consumers/$userId'
      preLoaderRoute: typeof AppLayoutConsumersUserIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app-layout/businesses/$businessId': {
      id: '/_app-layout/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof AppLayoutBusinessesBusinessIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutBookingsRoute: typeof AppLayoutBookingsRoute
  AppLayoutClassesRoute: typeof AppLayoutClassesRoute
  AppLayoutDashboardRoute: typeof AppLayoutDashboardRoute
  AppLayoutBusinessesBusinessIdRoute: typeof AppLayoutBusinessesBusinessIdRoute
  AppLayoutConsumersUserIdRoute: typeof AppLayoutConsumersUserIdRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutBookingsRoute: AppLayoutBookingsRoute,
  AppLayoutClassesRoute: AppLayoutClassesRoute,
  AppLayoutDashboardRoute: AppLayoutDashboardRoute,
  AppLayoutBusinessesBusinessIdRoute: AppLayoutBusinessesBusinessIdRoute,
  AppLayoutConsumersUserIdRoute: AppLayoutConsumersUserIdRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  HealthRoute: HealthRoute,
  SignInTesterRoute: SignInTesterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
