/**
 * Centralized error codes for the entire application.
 * 
 * Usage:
 * ```typescript
 * import { ERROR_CODES } from "../utils/errorCodes";
 * 
 * throw new ConvexError({
 *   message: "User not found",
 *   code: ERROR_CODES.RESOURCE_NOT_FOUND
 * });
 * ```
 * 
 * When adding new error codes:
 * 1. Add them to the appropriate category
 * 2. Use SCREAMING_SNAKE_CASE
 * 3. Make the name descriptive and unique
 * 4. Update existing code to use the centralized constants
 */
export const ERROR_CODES = {
    // Authentication & Authorization
    UNAUTHORIZED: 'UNAUTHORIZED',
    USER_ALREADY_ASSOCIATED_WITH_BUSINESS: 'USER_ALREADY_ASSOCIATED_WITH_BUSINESS',
    USER_NOT_ASSOCIATED_WITH_BUSINESS: 'USER_NOT_ASSOCIATED_WITH_BUSINESS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',

    // Validation Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',

    // Resource Errors
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

    // General Errors
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',

    // Booking Errors - Customer/Class Requirements
    MISSING_CUSTOMER: 'MISSING_CUSTOMER',
    MISSING_CLASS: 'MISSING_CLASS',
    INVALID_BOOKING_SOURCE: 'INVALID_BOOKING_SOURCE',

    // Booking Errors - Timing
    CLASS_STARTED: 'CLASS_STARTED',
    TOO_LATE: 'TOO_LATE',
    TOO_EARLY: 'TOO_EARLY',
    PAST_CANCELLATION_DEADLINE: 'PAST_CANCELLATION_DEADLINE',

    // Booking Errors - Capacity
    CLASS_FULL: 'CLASS_FULL',
    WAITLIST_FULL: 'WAITLIST_FULL',
    NO_SPACE_AVAILABLE: 'NO_SPACE_AVAILABLE',
    CAPACITY_TOO_LOW: 'CAPACITY_TOO_LOW',

    // Booking Errors - Credits & Status
    INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
    CLASS_CANCELLED: 'CLASS_CANCELLED',
    CLASS_COMPLETED: 'CLASS_COMPLETED',
    CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',
    WAIVER_REQUIRED: 'WAIVER_REQUIRED',

    // Booking Errors - Cancellation
    ALREADY_CANCELLED: 'ALREADY_CANCELLED',
    MARKED_NO_SHOW: 'MARKED_NO_SHOW',

    // Booking Errors - Waitlist
    NOT_WAITLISTED: 'NOT_WAITLISTED',

    // Booking Errors - Duplicates
    DUPLICATE_BOOKING: 'DUPLICATE_BOOKING',

    // Class Template Validation
    MISSING_NAME: 'MISSING_NAME',
    INVALID_START_TIME: 'INVALID_START_TIME',
    INVALID_DURATION: 'INVALID_DURATION',
    INVALID_CAPACITY: 'INVALID_CAPACITY',
    INVALID_CREDITS: 'INVALID_CREDITS',
    INVALID_WAITLIST_CAPACITY: 'INVALID_WAITLIST_CAPACITY',
    INVALID_RECURRENCE_RULE: 'INVALID_RECURRENCE_RULE',
    INVALID_STATUS: 'INVALID_STATUS',

    // Action Errors
    ACTION_NOT_ALLOWED: 'ACTION_NOT_ALLOWED',

    // Credit System Errors
    CREDIT_IDEMPOTENCY_KEY_REQUIRED: 'CREDIT_IDEMPOTENCY_KEY_REQUIRED',
    CREDIT_DESCRIPTION_REQUIRED: 'CREDIT_DESCRIPTION_REQUIRED',
    CREDIT_ENTRIES_REQUIRED: 'CREDIT_ENTRIES_REQUIRED',
    CREDIT_TRANSACTION_FAILED: 'CREDIT_TRANSACTION_FAILED',
    CREDIT_INVALID_ENTITY: 'CREDIT_INVALID_ENTITY',
    CREDIT_INVALID_AMOUNT: 'CREDIT_INVALID_AMOUNT',
    CREDIT_INVALID_ENTITY_TYPE: 'CREDIT_INVALID_ENTITY_TYPE',
    CREDIT_DOUBLE_ENTRY_VIOLATION: 'CREDIT_DOUBLE_ENTRY_VIOLATION',
} as const;

// Type for error codes
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];